-- Migration: Create clients table and security policies

-- 1. Create the table
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id) on delete cascade not null, -- Links data to the logged-in user
  name text not null,
  cpf text,
  lot text,
  parcel text,
  due_date date,
  value numeric, -- Storing as number is better for calculations
  status text check (status in ('Pago', 'A Vencer', 'Atrasado')),
  phone text,
  email text,
  address text,
  notes text,
  photo_url text, -- We will store the URL, not the base64 blob if possible in the future
  initials text -- Can be calculated on frontend, but storing for cache is fine
);

-- 2. Enable Row Level Security (RLS)
alter table public.clients enable row level security;

-- 3. Create Policies (Security Rules)

-- Policy: Users can only see their own clients
create policy "Users can view their own clients"
  on public.clients for select
  using (auth.uid() = user_id);

-- Policy: Users can insert their own clients
create policy "Users can insert their own clients"
  on public.clients for insert
  with check (auth.uid() = user_id);

-- Policy: Users can update their own clients
create policy "Users can update their own clients"
  on public.clients for update
  using (auth.uid() = user_id);

-- Policy: Users can delete their own clients
create policy "Users can delete their own clients"
  on public.clients for delete
  using (auth.uid() = user_id);

-- 4. Create Storage Bucket for Photos (Optional but recommended for later)
-- insert into storage.buckets (id, name, public) values ('client-photos', 'client-photos', true);
-- create policy "Authenticated users can upload photos" on storage.objects for insert with check (bucket_id = 'client-photos' and auth.role() = 'authenticated');
-- create policy "Users can view photos" on storage.objects for select using (bucket_id = 'client-photos');
